//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeElements.UpdateSystem.Windows.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeElements.UpdateSystem.Windows.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply delta patch on file &apos;{0}&apos;.
        /// </summary>
        internal static string UpdatesAvailableForm_ApplyDeltaPatch {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_ApplyDeltaPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UpdatesAvailableForm_Cancel {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog is empty.
        /// </summary>
        internal static string UpdatesAvailableForm_ChangelogIsEmpty {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_ChangelogIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect information....
        /// </summary>
        internal static string UpdatesAvailableForm_CollectInformation {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_CollectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file &apos;{0}&apos;.
        /// </summary>
        internal static string UpdatesAvailableForm_DownloadFile {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string UpdatesAvailableForm_Error {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates.
        /// </summary>
        internal static string UpdatesAvailableForm_InstallUpdates {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_InstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One new update available.
        /// </summary>
        internal static string UpdatesAvailableForm_NewUpdateAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates can be downloaded. Update from version {0} to {1}.
        /// </summary>
        internal static string UpdatesAvailableForm_NewUpdateCanBeDownloaded {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_NewUpdateCanBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new updates available.
        /// </summary>
        internal static string UpdatesAvailableForm_NewUpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_NewUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        internal static string UpdatesAvailableForm_ReleaseDate {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdatesAvailableForm_Update {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate file &apos;{0}&apos;.
        /// </summary>
        internal static string UpdatesAvailableForm_ValidateFile {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_ValidateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate tasks.
        /// </summary>
        internal static string UpdatesAvailableForm_ValidateTasks {
            get {
                return ResourceManager.GetString("UpdatesAvailableForm_ValidateTasks", resourceCulture);
            }
        }
    }
}
